# Generated by Django 2.2.4 on 2019-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_short', models.CharField(max_length=200)),
                ('question_text_long', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
